### ISSUE TITLE
Syntax error line Cookie.php

### ISSUE THREAD

**Issue by quevlu** [overclokk/cookie#1]
Hey,

I get the library via composer and when i try to use :
 
The file : 
overclokk/cookie/src/Cookie.php on line 103

The method :
public function forever( $name, $value, $expire = 31536000 * 5 ) {
		return $this->set( $name, $value, $expire );
	}

**Comment by overclokk** [comment]
Hi @byinff 
could you paste here the code you use and the error you receve?

**Comment by quevlu** [comment]
hi @overclokk.

I create a simple cookie object but i have error in forever function.

**Comment by overclokk** [comment]
What kind of error do you have?
Paste the code you used here in the comments.

**Comment by aviggngyv** [comment]
same error: 

> Parse error: syntax error, unexpected '*', expecting ')' in E:\phpStudy\WWW\print\vendor\overclokk\cookie\src\Cookie.php on line 103

**Comment by overclokk** [comment]
What version of php do you use?

**Comment by overclokk** [comment]
Fixed, it was the PHP version, now is PHP >= 5.3 compatible.
